baseURL = "https://hyeonseopjeong.github.io"
languageCode = "kr-ko"
title = "$HELLO_PROG^"
theme = "hugo-hello-programmer-theme"

disqusShortname = "XXXXXXXXXXXXXXX"

googleAnalytics = "UA-XXXXXXXXXX-X"

paginate = 7

[author]
    name = "Hyeonseop Jeong"
    email = "21600665@handong.edu"

[params]
    description = "desribe-your-site"
